import { Product } from './supabase';

export type ProductWithFeatured = Product & { featured?: boolean };

export const LOCAL_PRODUCTS: ProductWithFeatured[] = [
  {
    id: '1',
    name: 'Logitech MX Master 3S',
    description: 'Advanced wireless mouse with 8K DPI sensor, quiet clicks, and 70-day battery life.',
    price_xaf: 35000,
    brand: 'Logitech',
    specs: {
      sensor: '8,000 DPI',
      battery: '70 days',
      connectivity: 'Bluetooth, USB Receiver',
    },
    images: ['/images/logitech-mx-master-3s.png'],
    stock_status: 'in_stock',
    featured: true,
  },
  {
    id: '2',
    name: 'Logitech MX Keys S',
    description: 'Smart illuminated wireless keyboard with perfect stroke keys and smart shortcuts.',
    price_xaf: 28000,
    brand: 'Logitech',
    specs: {
      keys: 'Perfect Stroke',
      battery: '10 days (backlight on)',
      connectivity: 'Bluetooth, USB Receiver',
    },
    images: ['/images/logitech-mx-keys-s.png'],
    stock_status: 'in_stock',
    featured: true,
  },
  {
    id: '3',
    name: 'Keychron K2 Pro',
    description: 'Wireless mechanical keyboard with QMK/VIA support and hot-swappable switches.',
    price_xaf: 32000,
    brand: 'Keychron',
    specs: {
      switches: 'Hot-swappable Brown',
      battery: '80 hours',
      connectivity: 'Bluetooth, USB-C',
    },
    images: ['/images/keychron-k2-pro.png'],
    stock_status: 'in_stock',
    featured: true,
  },
  {
    id: '4',
    name: 'Logitech G502 Hero',
    description: 'High-performance gaming mouse with 25,600 DPI sensor and 11 programmable buttons.',
    price_xaf: 45000,
    brand: 'Logitech',
    specs: {
      sensor: '25,600 DPI',
      buttons: '11 programmable',
      weight: '121g (adjustable)',
    },
    images: ['/images/logitech-g502-hero.png'],
    stock_status: 'in_stock',
    featured: false,
  },
  {
    id: '5',
    name: 'Logitech Pebble Mouse 2',
    description: 'Slim, quiet, and portable wireless mouse with customizable middle button.',
    price_xaf: 25000,
    brand: 'Logitech',
    specs: {
      sensor: '4000 DPI',
      battery: '24 months',
      connectivity: 'Bluetooth, USB Receiver',
    },
    images: ['/images/logitech-pebble-mouse-2.png'],
    stock_status: 'in_stock',
    featured: false,
  },
  {
    id: '6',
    name: 'Anker PowerCore 20000',
    description: '20000mAh portable charger with PowerIQ and fast charging support.',
    price_xaf: 18000,
    brand: 'Anker',
    specs: {
      capacity: '20000mAh',
      output: '20W USB-C',
      weight: '345g',
    },
    images: ['/images/placeholder.svg'],
    stock_status: 'in_stock',
    featured: false,
  },
  {
    id: '7',
    name: 'Anker 737 Power Bank',
    description: '24000mAh high-capacity power bank with 140W total output.',
    price_xaf: 42000,
    brand: 'Anker',
    specs: {
      capacity: '24000mAh',
      output: '140W total',
      display: 'Smart IPS',
    },
    images: ['/images/anker-737.png'],
    stock_status: 'in_stock',
    featured: false,
  },
  {
    id: '8',
    name: 'Keychron Q1 Pro',
    description: 'Premium mechanical keyboard with 2.4G wireless, QMK/VIA, and all-metal body.',
    price_xaf: 48000,
    brand: 'Keychron',
    specs: {
      switches: 'Hot-swappable Red',
      battery: '100 hours (wireless)',
      connectivity: '2.4G, Bluetooth, USB-C',
    },
    images: ['/images/keychron-q1-pro.png'],
    stock_status: 'in_stock',
    featured: false,
  },
];
